# Generated by Django 3.0.2 on 2020-02-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pdf',
            field=models.ImageField(upload_to='room/pdfs'),
        ),
    ]
