# Generated by Django 3.0.2 on 2020-02-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
